# continuous
python algorithms/continuous/ddpg.py
python algorithms/continuous/gail.py
python algorithms/continuous/npg.py
python algorithms/continuous/ppo.py
python algorithms/continuous/sac_with_il.py
python algorithms/continuous/td3.py
python algorithms/continuous/td3bc.py

# discrete
python algorithms/discrete/a2c_with.il.py
python algorithms/discrete/c51.py
python algorithms/discrete/dqn.py
python algorithms/discrete/fqf.py
python algorithms/discrete/pg.py
python algorithms/discrete/ppo.py
python algorithms/discrete/qrdqn.py
python algorithms/discrete/rainbow.py
python algorithms/discrete/sac.py